// GENERATED by scripts/generate-ai-booking-catalogue.ts. Do not edit.
export const catalogue = {
  "event": "Trinidad Carnival 2027",
  "dates": [
    {
      "day": "monday",
      "label": "Carnival Monday",
      "date": "2027-02-08",
      "display": "Monday 8 February 2027"
    },
    {
      "day": "tuesday",
      "label": "Carnival Tuesday",
      "date": "2027-02-09",
      "display": "Tuesday 9 February 2027"
    }
  ],
  "venue": "the Hilton Hotel, Port of Spain",
  "currency": "USD",
  "whatsapp": "https://wa.me/18765090997",
  "google_rating": {
    "rating": 4.8,
    "count": 19,
    "as_of": "2026-10-07",
    "url": "https://www.google.com/maps?cid=3692744883055322374"
  },
  "gallery_url": "https://www.carnivalglamhub.com/#gallery",
  "inclusions": [
    "Shuttle",
    "Getting-dressed assistance",
    "Breakfast and refreshments",
    "Coffee and tea"
  ],
  "products": [
    {
      "id": "mon-makeup",
      "label": "Makeup only",
      "day": "monday",
      "price": 180,
      "tags": [
        "makeup"
      ],
      "image_url": "https://www.carnivalglamhub.com/images/ai-booking/makeup.webp",
      "image_alt": "Carnival makeup by Carnival Glam Hub"
    },
    {
      "id": "mon-makeup-photo",
      "label": "Makeup and photoshoot",
      "day": "monday",
      "price": 320,
      "tags": [
        "makeup",
        "photoshoot"
      ],
      "image_url": "https://www.carnivalglamhub.com/images/ai-booking/makeup-photo.webp",
      "image_alt": "Carnival makeup and costume photoshoot by Carnival Glam Hub"
    },
    {
      "id": "mon-photo",
      "label": "Photoshoot only",
      "day": "monday",
      "price": 160,
      "tags": [
        "photoshoot"
      ],
      "image_url": "https://www.carnivalglamhub.com/images/ai-booking/photo.webp",
      "image_alt": "Carnival photoshoot by Carnival Glam Hub"
    },
    {
      "id": "tue-makeup",
      "label": "Makeup only",
      "day": "tuesday",
      "price": 210,
      "tags": [
        "makeup"
      ],
      "image_url": "https://www.carnivalglamhub.com/images/ai-booking/makeup.webp",
      "image_alt": "Carnival makeup by Carnival Glam Hub"
    },
    {
      "id": "tue-makeup-photo",
      "label": "Makeup and photoshoot",
      "day": "tuesday",
      "price": 330,
      "tags": [
        "makeup",
        "photoshoot"
      ],
      "image_url": "https://www.carnivalglamhub.com/images/ai-booking/makeup-photo.webp",
      "image_alt": "Carnival makeup and costume photoshoot by Carnival Glam Hub"
    },
    {
      "id": "tue-photo",
      "label": "Photoshoot only",
      "day": "tuesday",
      "price": 160,
      "tags": [
        "photoshoot"
      ],
      "image_url": "https://www.carnivalglamhub.com/images/ai-booking/photo.webp",
      "image_alt": "Carnival photoshoot by Carnival Glam Hub"
    },
    {
      "id": "both-makeup",
      "label": "Makeup only",
      "day": "both",
      "price": 380,
      "tags": [
        "makeup"
      ],
      "image_url": "https://www.carnivalglamhub.com/images/ai-booking/makeup.webp",
      "image_alt": "Carnival makeup by Carnival Glam Hub"
    },
    {
      "id": "both-makeup-photo",
      "label": "Makeup and photoshoot",
      "day": "both",
      "price": 480,
      "tags": [
        "makeup",
        "photoshoot"
      ],
      "image_url": "https://www.carnivalglamhub.com/images/ai-booking/makeup-photo.webp",
      "image_alt": "Carnival makeup and costume photoshoot by Carnival Glam Hub"
    }
  ],
  "slot_times": [
    "04:00",
    "05:00",
    "06:00",
    "07:00",
    "08:00"
  ],
  "slot_capacity": 3,
  "terms": {
    "summary": [
      "Full payment is taken at booking. We reserve the right to require full payment at the time of booking for certain services, add-ons, group bookings or promotional rates. Where this applies, it is stated at checkout.",
      "Cancellation within 14 days of the Event. No refund is given if you cancel within 14 days before the Event. Bookings made within this period are non-refundable in full.",
      "A deposit or booking may be transferred to another Carnival Glam Hub event within 12 months of the original Event date. This includes transfers between territories, subject to availability at the receiving Hub. A transfer is allowed once per booking. A transfer must be requested at least 3 days before the Event. Requests made inside that window are not accepted.",
      "Please register at the Hub no later than 30 minutes before your confirmed appointment time.",
      "A 15 minute grace period applies from your confirmed appointment time."
    ],
    "url": "https://www.carnivalglamhub.com/policies"
  }
};
