import { useEffect } from "react";
import { Link } from "react-router-dom";
import Navbar from "@/components/landing/Navbar";
import Footer from "@/components/landing/Footer";
import StickyMobileCTA from "@/components/landing/StickyMobileCTA";

const SLUG = "caribbean-carnival-has-an-airlift-problem";
const URL = `https://www.carnivalglamhub.com/blogs/${SLUG}`;
const TITLE =
  "The Caribbean Carnival economy doesn\u2019t have a demand problem. It has an airlift problem.";
const META_TITLE = "The Caribbean Carnival airlift problem | Carnival Glam Hub";
const DESCRIPTION =
  "From inside the Caribbean Carnival economy, demand for Trinidad, Jamaica, Crop Over, Spice Mas, Caribana, Miami, and other regional Carnivals is strong. What\u2019s broken is the air capacity moving masqueraders between them.";
const META_DESCRIPTION =
  "Demand for Caribbean Carnival is strong. What\u2019s broken is inter-island air capacity. Kibwe McGann on the airlift problem stalling Carnival growth.";
const AUTHOR = "Kibwe McGann";
const DATE_PUBLISHED = "2026-05-29";
const FEATURED_IMAGE = "/linkedin-carnival-air-travel-post.svg";
const TAGS = [
  "Carnival Economy",
  "Caribbean Travel",
  "Airlift",
  "Carnival Infrastructure",
  "Carnival Glam Hub",
  "Trinidad Carnival",
  "Crop Over",
  "Spice Mas",
  "Caribana",
  "Miami Carnival",
  "Jamaica Carnival",
  "Saint Lucia Carnival",
  "Antigua Carnival",
];

const BODY_PARAGRAPHS: string[] = [
  "Working across 10 Carnival territories with __CGH__ has given me a clear view of how masqueraders plan their year. The industry spends a lot of time discussing costumes, events, sponsorship and tourism campaigns. One challenge receives surprisingly little attention.",
  "Getting people to the Carnival.",
  "The Caribbean has proven there is demand. Every year travellers spend thousands attending __TRINIDAD__ Carnival, Crop Over, Spice Mas, __STLUCIA__ Carnival, Antigua Carnival, Jamaica Carnival and others throughout the region. They buy costumes, book hotels, attend fetes, hire makeup, eat in restaurants. The demand exists. What is becoming difficult is moving people around the region efficiently enough to support it.",
  "One example that regularly surprises travellers is the Trinidad to Saint Lucia route. It is often cheaper to fly Port of Spain to Tobago and connect onto a British Airways service into Saint Lucia than to book a direct regional flight. Some travellers from Jamaica find more competitive options routing through Miami before returning to another Caribbean destination. When travellers create workarounds to avoid direct regional travel, that is a signal the market is not functioning efficiently.",
  "The issue isn\u2019t only airfare. Frequency and connectivity matter equally. Many regional routes don\u2019t operate daily, forcing travellers to extend trips beyond the actual event. A four-day Carnival can easily become a seven-day trip once flight schedules, accommodation costs and logistics are considered. For many visitors, that additional cost decides which Carnival they attend.",
  "What concerns me is that the wider economic impact rarely enters the conversation. Airlines understandably make decisions based on profitability. Governments have a different responsibility. They must weigh the economic value generated by the visitor once they arrive. That visitor doesn\u2019t just buy a plane ticket. They support hotels, restaurants, transport providers, costume designers, photographers, makeup artists, event promoters and countless small businesses.",
  "This is why governments and tourism authorities need to take a more active role in Carnival airlift discussions. Too often, additional flights appear only after demand has already peaked. By then, costume sections have closed, accommodation is limited, and travellers have committed elsewhere. The airline may benefit from higher fares. The wider economy loses spending.",
  "We have largely relied on market forces to solve this. Adam Smith\u2019s invisible hand is an important principle, but even free markets experience failures. When an industry as economically significant as Carnival is affected by limited competition, constrained capacity and inadequate connectivity, governments have a legitimate role to play in ensuring the market serves the broader interests of the country, not just the commercial interests of individual carriers.",
  "The Caribbean does not have a Carnival demand problem. It has an airlift problem. If we are serious about growing Carnival tourism, governments, tourism boards and airlines need to treat airlift as part of Carnival infrastructure rather than someone else\u2019s responsibility.",
  "Because no matter how strong the Carnival product becomes, its growth will always be limited by how easily people can get there.",
];

const PLAIN_BODY =
  BODY_PARAGRAPHS.map((p) =>
    p
      .replace(/__CGH__/g, "Carnival Glam Hub")
      .replace(/__TRINIDAD__/g, "Trinidad")
      .replace(/__STLUCIA__/g, "Saint Lucia")
  ).join("\n\n") +
  "\n\nKibwe McGann\nCofounder, Carnival Glam Hub";

type Segment =
  | { type: "text"; value: string }
  | { type: "link"; to: string; label: string };

const tokeniseParagraph = (paragraph: string): Segment[] => {
  const regex = /(__CGH__|__TRINIDAD__|__STLUCIA__)/g;
  const out: Segment[] = [];
  let last = 0;
  let match: RegExpExecArray | null;
  while ((match = regex.exec(paragraph)) !== null) {
    if (match.index > last) {
      out.push({ type: "text", value: paragraph.slice(last, match.index) });
    }
    if (match[1] === "__CGH__") {
      out.push({ type: "link", to: "/", label: "Carnival Glam Hub" });
    } else if (match[1] === "__TRINIDAD__") {
      out.push({ type: "link", to: "/trinidad-carnival-2027", label: "Trinidad" });
    } else {
      out.push({ type: "link", to: "/st-lucia", label: "Saint Lucia" });
    }
    last = match.index + match[1].length;
  }
  if (last < paragraph.length) {
    out.push({ type: "text", value: paragraph.slice(last) });
  }
  return out;
};

const AirliftProblem = () => {
  useEffect(() => {
    const previousTitle = document.title;
    document.title = META_TITLE;

    const setMeta = (
      selector: string,
      attr: "name" | "property",
      name: string,
      content: string
    ) => {
      let tag = document.head.querySelector<HTMLMetaElement>(selector);
      let created = false;
      if (!tag) {
        tag = document.createElement("meta");
        tag.setAttribute(attr, name);
        document.head.appendChild(tag);
        created = true;
      }
      const prev = tag.getAttribute("content");
      tag.setAttribute("content", content);
      return () => {
        if (created) tag?.remove();
        else if (prev !== null) tag?.setAttribute("content", prev);
      };
    };

    const restorers: Array<() => void> = [];
    restorers.push(setMeta('meta[name="description"]', "name", "description", META_DESCRIPTION));
    restorers.push(setMeta('meta[property="og:title"]', "property", "og:title", TITLE));
    restorers.push(setMeta('meta[property="og:description"]', "property", "og:description", DESCRIPTION));
    restorers.push(setMeta('meta[property="og:url"]', "property", "og:url", URL));
    restorers.push(setMeta('meta[property="og:type"]', "property", "og:type", "article"));
    restorers.push(setMeta('meta[name="twitter:title"]', "name", "twitter:title", TITLE));
    restorers.push(setMeta('meta[name="twitter:description"]', "name", "twitter:description", DESCRIPTION));

    // Canonical
    let canonical = document.head.querySelector<HTMLLinkElement>('link[rel="canonical"]');
    const prevCanonical = canonical?.getAttribute("href") ?? null;
    let createdCanonical = false;
    if (!canonical) {
      canonical = document.createElement("link");
      canonical.setAttribute("rel", "canonical");
      document.head.appendChild(canonical);
      createdCanonical = true;
    }
    canonical.setAttribute("href", URL);

    // Article JSON-LD
    const today = new Date().toISOString().slice(0, 10);
    const articleSchema = {
      "@context": "https://schema.org",
      "@type": "Article",
      headline: TITLE,
      description: DESCRIPTION,
      datePublished: DATE_PUBLISHED,
      dateModified: today,
      author: { "@type": "Person", name: AUTHOR },
      publisher: {
        "@type": "Organization",
        name: "Carnival Glam Hub",
        logo: {
          "@type": "ImageObject",
          url: "https://www.carnivalglamhub.com/logo.png",
        },
      },
      image: [`https://www.carnivalglamhub.com${FEATURED_IMAGE}`],
      mainEntityOfPage: { "@type": "WebPage", "@id": URL },
      keywords: TAGS.join(", "),
      articleBody: PLAIN_BODY,
    };
    const articleScript = document.createElement("script");
    articleScript.type = "application/ld+json";
    articleScript.textContent = JSON.stringify(articleSchema);
    document.head.appendChild(articleScript);

    const breadcrumbSchema = {
      "@context": "https://schema.org",
      "@type": "BreadcrumbList",
      itemListElement: [
        { "@type": "ListItem", position: 1, name: "Home", item: "https://www.carnivalglamhub.com/" },
        { "@type": "ListItem", position: 2, name: "Journal", item: "https://www.carnivalglamhub.com/blogs" },
        { "@type": "ListItem", position: 3, name: TITLE, item: URL },
      ],
    };
    const breadcrumbScript = document.createElement("script");
    breadcrumbScript.type = "application/ld+json";
    breadcrumbScript.textContent = JSON.stringify(breadcrumbSchema);
    document.head.appendChild(breadcrumbScript);

    return () => {
      document.title = previousTitle;
      restorers.forEach((r) => r());
      if (createdCanonical) canonical?.remove();
      else if (prevCanonical !== null) canonical?.setAttribute("href", prevCanonical);
      articleScript.remove();
      breadcrumbScript.remove();
    };
  }, []);

  // First-mention link tracking
  let cghLinked = false;
  let trinidadLinked = false;
  let stLuciaLinked = false;

  const renderParagraph = (paragraph: string, idx: number) => {
    const segments = tokeniseParagraph(paragraph);
    return (
      <p key={idx} className="font-body text-foreground/80 leading-[1.8] text-base sm:text-lg mb-6">
        {segments.map((seg, i) => {
          if (seg.type === "text") return <span key={i}>{seg.value}</span>;
          let shouldLink = false;
          if (seg.label === "Carnival Glam Hub" && !cghLinked) {
            shouldLink = true;
            cghLinked = true;
          } else if (seg.label === "Trinidad" && !trinidadLinked) {
            shouldLink = true;
            trinidadLinked = true;
          } else if (seg.label === "Saint Lucia" && !stLuciaLinked) {
            shouldLink = true;
            stLuciaLinked = true;
          }
          return shouldLink ? (
            <Link
              key={i}
              to={seg.to}
              className="text-primary underline underline-offset-2 decoration-primary/30 hover:decoration-primary"
            >
              {seg.label}
            </Link>
          ) : (
            <span key={i}>{seg.label}</span>
          );
        })}
      </p>
    );
  };

  const formattedDate = new Date(DATE_PUBLISHED).toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });

  return (
    <div className="min-h-screen bg-background text-foreground">
      <Navbar />
      <main className="pt-28 sm:pt-32">
        <article className="py-10 sm:py-14 lg:py-18">
          <div className="container mx-auto px-4 sm:px-6 max-w-2xl">
            <Link
              to="/blogs"
              className="inline-flex items-center gap-2 font-body text-xs uppercase tracking-[0.15em] text-muted-foreground hover:text-primary transition-colors mb-10 group"
            >
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="transition-transform group-hover:-translate-x-1">
                <path d="M19 12H5" />
                <path d="m12 19-7-7 7-7" />
              </svg>
              All Posts
            </Link>

            <div className="mb-4 flex flex-wrap gap-2">
              {TAGS.map((t) => (
                <span
                  key={t}
                  className="inline-block rounded-full border border-border bg-card/60 px-3 py-1 font-body text-[11px] uppercase tracking-[0.12em] text-muted-foreground"
                >
                  {t}
                </span>
              ))}
            </div>

            <h1
              className="font-display text-3xl sm:text-4xl lg:text-[2.75rem] font-bold leading-[1.15] tracking-tight mb-6"
              style={{ textWrap: "balance" } as React.CSSProperties}
            >
              {TITLE}
            </h1>

            <div className="flex items-center gap-3 mb-8 pb-8 border-b border-border">
              <div className="font-body text-sm">
                <p className="font-semibold text-foreground leading-tight">{AUTHOR}</p>
                <p className="text-muted-foreground text-xs mt-0.5">
                  <time dateTime={DATE_PUBLISHED}>{formattedDate}</time> · 5 min read
                </p>
              </div>
            </div>

            {/* Featured image placeholder (asset not yet uploaded) */}
            <div
              className="mb-10 -mx-4 sm:mx-0 rounded-none sm:rounded-2xl border border-dashed border-primary/40 bg-primary/5 px-6 py-16 text-center"
              role="img"
              aria-label="Featured image placeholder awaiting upload from Kibwe"
            >
              <p className="font-body text-xs uppercase tracking-[0.2em] text-primary font-semibold mb-2">
                Featured Image Placeholder
              </p>
              <p className="font-body text-sm text-muted-foreground">
                Awaiting upload from Kibwe — image will be swapped in once delivered.
              </p>
            </div>

            <div>
              {BODY_PARAGRAPHS.map((p, i) => renderParagraph(p, i))}

              <div className="mt-10 pt-6 border-t border-border">
                <p className="font-body text-foreground/80 leading-[1.8] text-base sm:text-lg mb-1">
                  <Link
                    to="/about"
                    className="text-primary underline underline-offset-2 decoration-primary/30 hover:decoration-primary font-semibold"
                  >
                    Kibwe McGann
                  </Link>
                </p>
                <p className="font-body text-muted-foreground text-sm">
                  Cofounder, Carnival Glam Hub
                </p>
              </div>
            </div>

            <div className="mt-16 pt-8 border-t border-border flex items-center justify-between">
              <Link
                to="/blogs"
                className="inline-flex items-center gap-2 rounded-full border border-border px-5 py-2.5 font-body text-sm font-medium text-foreground transition-all hover:border-primary hover:text-primary group"
              >
                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="transition-transform group-hover:-translate-x-1">
                  <path d="M19 12H5" />
                  <path d="m12 19-7-7 7-7" />
                </svg>
                More Posts
              </Link>
            </div>
          </div>
        </article>
      </main>
      <Footer />
      <StickyMobileCTA />
    </div>
  );
};

export default AirliftProblem;