// Generates the AI booking app catalogue from src/data. Run on predev and
// prebuild. Never hand-edit supabase/functions/glam-hub-mcp/catalogue.json.
import { mkdirSync, writeFileSync } from "fs";
import { dirname, resolve } from "path";
import { buildAiBookingCatalogue } from "../src/data/aiBookingCatalogue";

const OUT = resolve(process.cwd(), "supabase/functions/glam-hub-mcp/catalogue.json");
// TypeScript copy for shared code (JSON in _shared is not bundled on deploy).
const SHARED = resolve(process.cwd(), "supabase/functions/_shared/glamHubCatalogue.ts");

try {
  const json = `${JSON.stringify(buildAiBookingCatalogue(), null, 2)}\n`;
  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, json, "utf8");
  writeFileSync(SHARED, `// GENERATED by scripts/generate-ai-booking-catalogue.ts. Do not edit.\nexport const catalogue = ${json.trim()};\n`, "utf8");
  console.log(`[ai-booking-catalogue] wrote ${OUT} and ${SHARED}`);
} catch (err) {
  console.error("[ai-booking-catalogue] FAILED:", err instanceof Error ? err.message : err);
  process.exit(1);
}
